### ISSUE TITLE
[UI] Adding an attractive footer 

### ISSUE THREAD

**Issue by HarshitaJaiswal5** [R0Y15/WeatherNow#124]
Description: 
This PR introduces a sleek and visually appealing footer section to enhance the overall user experience and provide a polished finish to the website. The new footer includes essential links for navigation, social media icons for better engagement, and copyright information for professionalism. It is designed to be responsive across different devices, ensuring a consistent user interface.

Key Features:

1. Navigation Links: Quick access to important sections of the site.
2. Social Media Integration: Icons for seamless connection with popular platforms.
3. Responsive Design: Fully adaptable for both mobile and desktop views.
4. Custom Styling: Clean and modern look to match the website’s theme.

**Comment by HarshitaJaiswal5** [comment]
@R0Y15  can you assign me this issue under hacktoberfest

**Comment by R0Y15** [comment]
Hello @HarshitaJaiswal5, I'm glad that you found a potential in contributing to this project however this project is a simple web application for providing weather data, and I don't feel so that there is any need for such descriptive footer. 
If you still wish to proceed, you can but there would be chances of getting the pr merged. 

Good luck.
