### ISSUE TITLE
Enhancing UI using REACT

### ISSUE THREAD

**Issue by SowmikDey** [R0Y15/WeatherNow#79]
/assign

**Comment by R0Y15** [comment]
Sure, I'd love to know what all you are planning to implement.

**Comment by SowmikDey** [comment]
please add hacktoberfest label to the issue

**Comment by R0Y15** [comment]
@SowmikDey any updates on this issue?

**Comment by SowmikDey** [comment]
I have a hackathon tomorrow so I am busy...but I will provide the complete project within 24th october plss give me a little time I am not only just enhancing the UI but also recreating the entire website where hourly weather data with icons will be shown,weather data by city name as well as location also will be shown & I am trying to make this website look good

It's just all messedup right now I am giving a small preview don't judge it right now

![image](https://github.com/user-attachments/assets/9cdab123-872e-4071-8546-025f180ced28)

a little file structure is also shown below

![image](https://github.com/user-attachments/assets/403bb309-03a4-4f8f-9d0c-cab507902a90)

**Comment by SowmikDey** [comment]
Due to cyclone the wifi is not working so it would take more time so pls wait till I finish

**Comment by R0Y15** [comment]
@SowmikDey Hi, I hope this message finds you well. as per the last conversation, I can see that you are freshly preparing a new project and not contributing to the existing one. This repository is not an idea which needs to be implemented but rather a deployed project which can be made better. so I request you to please make a contribution rather than making everything from scratch.

I'm closing this issue, please raise an issue if you have some idea of enhancement.
Regards.
