### ISSUE TITLE
Enchancement of the Search result

### ISSUE THREAD

**Issue by R0Y15** [R0Y15/WeatherNow#8]
The goal is to make the search result appear inside a card

for reference: 
![image](https://github.com/R0Y15/WeatherNow/assets/66421958/5347989e-b418-46be-9258-642995e8eee8)

or 
![image](https://github.com/R0Y15/WeatherNow/assets/66421958/fa753f30-9d2d-4559-a6fd-667fdeb88635)

**Comment by Paul-Annay** [comment]
![image](https://github.com/R0Y15/WeatherNow/assets/84911232/857d43d7-b9cf-4f77-b4ea-4b95d9aa582d)

Hi, so basically you want the output to be rendered in a properly styled card element instead of the plain text format (shown in the image) it is currently in. If this is correct then can I work on this? I think I might be able to add some interesting styles to this.

**Comment by R0Y15** [comment]
> ![image](https://user-images.githubusercontent.com/84911232/272871065-857d43d7-b9cf-4f77-b4ea-4b95d9aa582d.png)
> 
> Hi, so basically you want the output to be rendered in a properly styled card element instead of the plain text format (shown in the image) it is currently in. If this is correct then can I work on this? I think I might be able to add some interesting styles to this.

yes you're correct, I'm assigning this to you, happy hacking mate.

**Comment by Paul-Annay** [comment]
@R0Y15 
![image](https://github.com/R0Y15/WeatherNow/assets/84911232/49bf0f36-2e7e-4a82-be0b-9aa84c8df3ef)

Will this do?

**Comment by R0Y15** [comment]
> @R0Y15 ![image](https://user-images.githubusercontent.com/84911232/272888645-49bf0f36-2e7e-4a82-be0b-9aa84c8df3ef.png)
> 
> Will this do?

this looks pretty clean.. go for a PR.. if possible add the other parameters as well so that they can be utilized later (if possible)
